# Generated by Django 2.2 on 2019-04-23 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('descricao', models.CharField(max_length=200)),
                ('datacriacao', models.DateTimeField()),
                ('alerta', models.BooleanField()),
                ('dataevento', models.DateTimeField()),
            ],
        ),
    ]
